### ISSUE TITLE
Two CSS bugs

### ISSUE THREAD

**Issue by Meng-MiamiOH** [Miamiohlibs/Dashboard#12]
known bugs:

- click on the hamburger menu's icon, offcanvas doesn't show up

- the close icon inside offcanvas (top-right) can not change color

**Comment by kenirwin** [comment]
@Meng-MiamiOH suggests upgrading to new bootstrap version

**Comment by Meng-MiamiOH** [comment]
Bootstrap version is now at 5.0.2, with icon 1.5.0

**Comment by Meng-MiamiOH** [comment]
Close button on offcanvas, color changed to white.
![image](https://user-images.githubusercontent.com/43998638/124782842-91981280-df12-11eb-8b7c-852376b24deb.png)
