### ISSUE TITLE
downgrade to jquery 3.5.0?

### ISSUE THREAD

**Issue by kenirwin** [Miamiohlibs/Dashboard#38]
jquery v. 3.6.0 includes a change that breaks some functionality in the select2 pulldown feature used in the preview route (/preview) 

@Meng-MiamiOH - do you know of any reason we need jquery 3.6 particularly? If not, perhaps we can downgrade the version in the header.ejs file to 3.5.0. 

For now, I'm just using a separate header for the preview.ejs file, but that's not a great option if we can do better.

**Comment by Meng-MiamiOH** [comment]
Give it a try to downgrade jQuery. Check on the heavily jQuery-involved functions, such as offcanvas. If no functions are broken, then downgrading jQuery works for Bootstrap 5.

**Comment by kenirwin** [comment]
Thanks @Meng-MiamiOH -- it looks ok, so I'm merging the change in #40
